### ISSUE TITLE
ORBAT Group Markers not loading for some clients. (ALiVE Only)

### ISSUE THREAD

**Issue by ryanparsons7** [TMF3/TMF#111]
We have had this issue with some of our players in our group, especially myself where we would load a mission and upon reaching the briefing screen some people cannot see GROUP markers, but can see the specialized unit markers (Such as Medics and SLs). 

This also makes the ORBAT section of the briefing to present the wrong information about groups, showing the delta "Alpha 1-1" callsign instead of a custom callsign assigned to the group via the editor.

Shown in the screenshot below (Map Markers should appear at the USS Freedom marker):
![20170525211919_1](https://cloud.githubusercontent.com/assets/13571100/26471091/1f782b66-4198-11e7-9823-389b4667da7f.jpg)

This only occurs when running an ALiVE mission, works flawlessly on normal missions.

I run the "createBriefingPage" function via the debug menu after loading into the mission, another ORBAT briefing page appears with the correct information including the markers besides the group names.

And if I go back to the lobby, then rejoin the active mission and respawn myself, the markers appear on ORBAT and the map correctly.

Hopefully a solution can be found and thank you guys so much for this framework!

EDIT:
This ONLY occurs on dedicated server, forgot to mention.

**Comment by Sniperhid** [comment]
I must admit when this was first made I was pretty perplexed as to what was occurring and it seemed like something that Alive would be doing. Recently we have begun seeing the briefing page display 'Alpha 1-1' when groups do have names. 

It seems that as of new arma patches it is taking longer group information to be synchronised. My suspicions are that ALiVE casts a bigger initial load meaning that more often than not it takes longer.

In #163 I increased the delay before the orbat briefing page and markers are setup from 0.5 to 1.5 seconds. Hopefully this also fixes it for Alive as well, if not a longer delay may be necessary. I really wish there was a better method for finding out when groups are sync rather than just increasing the time.
