### ISSUE TITLE
[Request] Add vestItems[] and uniformItems[]

### ISSUE THREAD

**Issue by crowmium** [TMF3/TMF#121]
Functionality would be identical to backpackItems[] = {};

This would allow someone OCD like me to put items in their proper places (i.e. magazines go in the vest, small items go in uniform pockets, etc.). It would also allow people to standardize the way gear is sorted so players could find it easily (i.e. your medical supplies will always be in the uniform, etc.),

Thanks for all the hard work. I really appreciate this mod. It makes my mission making 10x easier.

**Comment by cptnnick** [comment]
Hey chrowmium,

Glad to hear you're enjoying using TMF. We built TMF to allow mission makers to accomplish some of the more advanced tasks even if they're still not very familiar with scripting mission features in Arma 3, especially in MP.

Most of our features are made with the intermediate level of mission maker in mind. This means we sometimes abstract things down to a level where less things can go wrong.

AssignGear is one of these areas, since player (and enemy) gear is often a very important and noticeable aspect of a mission. That's why it's designed in a way that not a lot of things can go wrong if for example uniform sizes and assigned items mismatch. By abstracting the place where items get added, they can overflow from the uniform into the backpack, and finally into the backpack in case of mismatch.

The backpack is a special occasion since backpacks can be accessible by other players when you're down or otherwise unable to interact. For example, it makes it easier to grab important medical supplies, rockets, or ammo belts from other players.

Adding in a vestItems[] and uniformItems[] would take away this level of abstraction. It would be possible to default to the current system, and only use vestItems[] or uniformitems[] when such an entry is present, but since the way inheritance in the gear configs is set up it won't always be obvious to missionmakers if loadout will be determined by the default entry or the more specific entries. That's why we won't be implementing this feature.

However, you're more than free to branch the assignGear component and add these in yourself. You'll have to create the gearfiles set up with these new parameters. You'll have to modify fn_assignGear.sqf to both load in these new entries into variables and add them to the unit after the uniform has been assigned. You'll have to modify fn_additems.sqf or make your own variants in order to specify if the item / magazine should be added to the uniform or vest, too.
