### ISSUE TITLE
ALiVE Issues

### ISSUE THREAD

**Issue by ryanparsons7** [TMF3/TMF#173]
After trying again to setup ALiVE with my group alongside TMF, some different issues have come up:

**Take note, issues only occur on dedicated server. Everything works fine via Local Multiplayer**
- ORBAT markers appear at the bottom left corner without details, just appear blank
![bug1](https://user-images.githubusercontent.com/13571100/32415227-19777156-c22e-11e7-9c32-467efd9e72d3.jpg)
- Some ACRE2 Radios do not get assigned correctly
![bug2](https://user-images.githubusercontent.com/13571100/32415228-1f88c75c-c22e-11e7-8033-4ef8874633e8.jpg)

Would there be a way of just initializing all the ORBAT and ACRE2 give-outs after the briefing screen is passed? Not having the markers and ACRE2 info on the briefing page isn't a big problem for me.

**Comment by ryanparsons7** [comment]
Seemed to fix the marker issue by increasing the delay to a massive value (120 Seconds).

**Comment by Sniperhid** [comment]
I think I finally have an idea to solve this. My assumption is that all variables to sent to clients go into a queue I am also assuming their is no preference in this system.

The fundamental issue here is that the code was running on clients before the vars were recieved. I suggest implementing a global variable in common "GVAR(vars_sent) = true` on server and sending its value to the client after all inits and then waiting for this variable to sent. If it is truly sent last and we wait for this client all should be golden.

As group variables are initialised the frame after init (because of engine bug) it would need to 2 frames in aka double use of CBA execute next frame.
