### ISSUE TITLE
BIS_fnc_endMissionServer does not end mission if players are in spectator

### ISSUE THREAD

**Issue by Freddo3000** [TMF3/TMF#199]
https://community.bistudio.com/wiki/BIS_fnc_endMissionServer
The function when run with the "SideScore" parameter successfully ends the mission for players who are still alive and proceeds to kick them out, however players who are in spectator does not receive the mission ended effect, nor do they get kicked out to the lobby.

**Comment by Freddo3000** [comment]
The same seems to apply to BIS_fnc_endMission.

**Comment by Sniperhid** [comment]
This is because `BIS_fnc_endMissionServer` uses sides to determine who to send the message to the end mission to. This is a vanilla issue spectators use sideLogic - This is also a problem for headless clients as well. My advice is stay away from this function.

We have an endMission function in tmf `tmf_common_fnc_endMission` that is intended to be called on the server.

When you call `["END1"] call tmf_common_fnc_endMission` it will end mission on all clients. It is not required to use this function at all (more of a hangover when we used OCAP to get OCAP export working properly.
